name: Python application
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@4.2.2
            - name: Python Syntax Checker
              uses: cclaus/Find-Python-syntax-errors-action@v1.0.0